export enum IButtonType {
    DANGER = 'danger',
    DROPDOWN = 'dropdown',
    LIGHT = 'light',
    DARK = 'dark',
    LINK = 'link',
    LINK_DANGER = 'link-danger',
    LINK_TEXT = 'link-text',
    PRIMARY = 'primary',
    SECONDARY = 'secondary',
    SUCCESS = 'success',
    WARNING = 'warning',
    WHITE = 'white',
    GRADIENT_PRIMARY = 'gradient-primary',
}
