export enum BannerType {
    ACCEPTED = 'ACCEPTED',
    DOCUMENTS = 'DOCUMENTS',
    DOCUMENTS_ALERT = 'DOCUMENTS_ALERT',
    HOUSE = 'HOUSE',
    HOUSE_ALERT = 'HOUSE_ALERT',
    LIGHT = 'LIGHT',
    LOADING = 'LOADING',
    MAIL_LETTER = 'MAIL_LETTER',
    SIGN = 'SIGN',
    UPLOAD = 'UPLOAD',
}
