import {
    ISupplierLogo,
    TypeCommodity,
} from 'src/common/ui/supplier/model/supplier.model';

export const config: ISupplierLogo[] = [
    {
        alt: 'logo - Alpiq CZ',
        logoUrl: '/assets/images/suppliers/logo_alpiq-hover.svg',
        logoUrlHover: '/assets/images/suppliers/logo_alpiq-hover.svg',
        supplierUrl: '',
        title: 'Alpiq CZ',
        width: 81,
        typeCommodity: TypeCommodity.POWER,
    },
    {
        alt: 'logo - Bohemia Energy entity s.r.o.',
        logoUrl: '/assets/images/suppliers/logo_bohemia-energy-hover.svg',
        logoUrlHover: '/assets/images/suppliers/logo_bohemia-energy-hover.svg',
        supplierUrl: '',
        size: 'sm',
        title: 'Bohemia Energy entity s.r.o.',
        width: 185,
        typeCommodity: TypeCommodity.BOTH,
    },
    {
        alt: 'logo - EP Energy Trading a.s.',
        logoUrl: '/assets/images/suppliers/logo_ep-energy-trading-hover.svg',
        logoUrlHover: '/assets/images/suppliers/logo_ep-energy-trading-hover.svg',
        supplierUrl: '',
        title: 'EP Energy Trading a.s.',
        width: 75,
        typeCommodity: TypeCommodity.BOTH,
    },
    {
        alt: 'logo - CARBOUNION BOHEMIA, spol. s r. o.',
        logoUrl: '/assets/images/suppliers/logo_carbounion-bohemia@2x-hover.png',
        logoUrlHover: '/assets/images/suppliers/logo_carbounion-bohemia@2x-hover.png',
        supplierUrl: '',
        size: 'xl',
        title: 'CARBOUNION BOHEMIA, spol. s r. o.',
        width: 70,
        typeCommodity: TypeCommodity.BOTH,
    },
    {
        alt: 'logo - Yello Energy',
        logoUrl: '/assets/images/suppliers/logo_yello-energy-hover.svg',
        logoUrlHover: '/assets/images/suppliers/logo_yello-energy-hover.svg',
        supplierUrl: '',
        size: 'xl',
        title: 'Yello Energy',
        width: 54,
        typeCommodity: TypeCommodity.BOTH,
    },
    {
        alt: 'logo - Pražská plynárenská a.s.',
        logoUrl: '/assets/images/suppliers/logo_prazska-plynarenska-hover.svg',
        logoUrlHover: '/assets/images/suppliers/logo_prazska-plynarenska-hover.svg',
        supplierUrl: '',
        size: 'xl',
        title: 'Pražská plynárenská a.s.',
        width: 134,
        typeCommodity: TypeCommodity.BOTH,
    },
];
