import { CommodityType } from 'src/common/graphql/models/supply.model';
import { ISupplyPointOffer } from 'src/common/graphql/models/offer.model';

export const offerConfig1: ISupplyPointOffer = {
    id: 0,
    supplier: {
        id: '',
        name: 'PRE',
        vatNumber: '',
        logoPath: '',
        sampleDocuments: [],
    },
    commodityType: CommodityType.POWER,
    name: '',
    validFrom: '2019-03-12T22:59:12.133Z',
    validTo: new Date(new Date().getTime() + 3600 * 1000 * 24).toISOString(),
    benefits: [
        'Žárovka LED',
        'Žárovka LED žárovka',
        'Žárovka LED',
        'Žárovka LED žárovka',
    ],
    deliveryFrom: '',
    deliveryTo: '',
    deliveryLength: 1,
    permanentPaymentPrice: 823.00,
    priceGas: 0,
    priceNT: 3.14,
    priceVT: 3.54,
    accountingRegulatedPrice: 1,
    consumptionPriceNT: 1,
    consumptionPriceVT: 1,
    distributionPriceByCapacity: 1,
    distributionPriceByConsumptionNT: 1,
    distributionPriceByConsumptionVT: 1,
    energyTaxRegulatedPrice: 1,
    marketOrganizerRegulatedPrice: 1,
    monthlyConsumptionFee: 1,
    renewableEnergyRegulatedPrice: 1,
    systemServicesRegulatedPrice: 1,
    totalPrice: 1,
    unit: 'kWH',
};

export const offerConfig2: ISupplyPointOffer = {
    benefits: [
        'LED Lorem žárovka',
        'LED Lorem',
        'LED Lorem žárovka',
        'LED Lorem',
    ],
    commodityType: CommodityType.POWER,
    deliveryFrom: '',
    deliveryTo: '',
    deliveryLength: 1,
    id: 0,
    name: '',
    permanentPaymentPrice: 869.00,
    priceGas: 0,
    priceNT: 2.64,
    priceVT: 6.54,
    supplier: {
        id: '',
        name: 'Pražská plynárenská',
        vatNumber: '',
        logoPath: '',
        sampleDocuments: [],
    },
    validFrom: '2019-03-12T22:59:12.133Z',
    validTo: new Date(new Date().getTime() + 3600 * 1000 * 24).toISOString(),
    accountingRegulatedPrice: 1,
    consumptionPriceNT: 1,
    consumptionPriceVT: 1,
    distributionPriceByCapacity: 1,
    distributionPriceByConsumptionNT: 1,
    distributionPriceByConsumptionVT: 1,
    energyTaxRegulatedPrice: 1,
    marketOrganizerRegulatedPrice: 1,
    monthlyConsumptionFee: 1,
    renewableEnergyRegulatedPrice: 1,
    systemServicesRegulatedPrice: 1,
    totalPrice: 1,
    unit: 'kWH',
};

export const offerConfig3: ISupplyPointOffer = {
    benefits: [
        'LED Lorem žárovka',
        'LED Lorem',
        'LED Lorem žárovka',
        'LED Lorem',
    ],
    commodityType: CommodityType.POWER,
    deliveryFrom: '',
    deliveryTo: '',
    deliveryLength: 1,
    id: 0,
    name: '',
    permanentPaymentPrice: 880.00,
    priceGas: 0,
    priceNT: 2.64,
    priceVT: 6.54,
    supplier: {
        id: '',
        name: 'ČEZ',
        vatNumber: '',
        logoPath: '',
        sampleDocuments: [],
    },
    validFrom: '2019-03-12T22:59:12.133Z',
    validTo: new Date(new Date().getTime() + 3600 * 1000 * 24).toISOString(),
    accountingRegulatedPrice: 1,
    consumptionPriceNT: 1,
    consumptionPriceVT: 1,
    distributionPriceByCapacity: 1,
    distributionPriceByConsumptionNT: 1,
    distributionPriceByConsumptionVT: 1,
    energyTaxRegulatedPrice: 1,
    marketOrganizerRegulatedPrice: 1,
    monthlyConsumptionFee: 1,
    renewableEnergyRegulatedPrice: 1,
    systemServicesRegulatedPrice: 1,
    totalPrice: 1,
    unit: 'kWH',
};
