import { IOffer } from 'src/common/graphql/models/offer.model';
import { CommodityType } from 'src/common/graphql/models/supply.model';

export const offerConfig: IOffer = {
    greenEnergy: false,
    status: null,
    subject: null,
    benefits: [
        {
            name: 'Žárovka LED Lorem',
            url: 'https://www.seznam.cz/',
        },
        {
            name: 'Žárovka LED Lorem',
            url: 'https://www.seznam.cz/',
        },
        {
            name: 'Žárovka LED Lorem',
            url: 'https://www.seznam.cz/',
        },
    ],
    commodityType: CommodityType.POWER,
    deliveryFrom: '',
    deliveryTo: '',
    deliveryLength: 1,
    id: '0',
    name: '',
    permanentPaymentPrice: 823.0,
    priceGas: 0,
    priceNT: 0,
    priceVT: 3.54,
    supplier: {
        id: '',
        name: 'PRE',
        vatNumber: '',
        logoPath: '',
        sampleDocuments: [],
    },
    validFrom: '2019-03-12T22:59:12.133Z',
    validTo: new Date(new Date().getTime() + 3600 * 1000 * 24).toISOString(),
    accountingRegulatedPrice: 0,
    consumptionPriceNT: 0,
    consumptionPriceVT: 0.1,
    distributionPriceByCapacity: 11,
    distributionPriceByConsumptionNT: 0,
    distributionPriceByConsumptionVT: 1.92,
    energyTaxRegulatedPrice: 0.02,
    marketOrganizerRegulatedPrice: 6.93,
    monthlyConsumptionFee: 100,
    renewableEnergyRegulatedPrice: 0.41,
    systemServicesRegulatedPrice: 0.06,
    totalPrice: 145.72,
    unit: 'MWh',
    priceGasWithVAT: 11,
    priceNTWithVAT: 0,
    priceVTWithVAT: 1.92,
};
