export const BAR_PLOT_CONSTS = {
    LIMIT_FOR_ROTATION_LABEL_TEXT: 60,
    PADDING_BETWEEN_ROWS: 0.05,
    ROTATION_LABEL_MARGIN: 15,
    COL_MARGIN_BOTTOM: 25,
    AXIS_MARGIN_TOP: 20,
    AXIS_PADDING: 10,
};
