import {
    DASHBOARD,
    OFFER_SELECTION,
    REQUEST,
    SECURED,
    SUPPLY_POINT_REQUEST,
} from './paths';

export const ROUTER_SECURED_REQUEST_SUPPLY_POINT = `/${SECURED}/${REQUEST}/${SUPPLY_POINT_REQUEST}`;
export const ROUTER_SECURED_REQUEST_OFFER_SELECTION = `/${SECURED}/${REQUEST}/${OFFER_SELECTION}`;
export const ROUTER_SECURED_DASHBOARD = `/${SECURED}/${DASHBOARD}`;
