export enum ContractActions {
    NONE = 'NONE',
    TERMINATE_CONTRACT = 'TERMINATE_CONTRACT',
    REMOVE_CONTRACT = 'REMOVE_CONTRACT',
    LEAVE_CONTRACT = 'LEAVE_CONTRACT',
    TRANSFER_SUPPLY_POINT = 'TRANSFER_SUPPLY_POINT',
    INTERRUPT_AUTOMATIC_PROLONGATION = 'INTERRUPT_AUTOMATIC_PROLONGATION',
}
